// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperSearcher.DAL.Contexts;

namespace SuperSearcher.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("SuperSearcher.DAL.Entities.SearchRequest", b =>
                {
                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT");

                    b.Property<string>("fromFolder")
                        .HasColumnType("TEXT");

                    b.ToTable("allRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
